apiVersion: v1
kind: Pod
metadata:
  name: contador-cue
spec:
  containers:
    - name: contenedor-1
      image: northpoint/prueba-2
      command: ["python3","test_m3u8.py"]
      imagePullPolicy: Always
