# Establecer la imagen base
FROM python:3.11

 

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia el archivo de requisitos y ejecuta pip para instalar las dependencias
RUN pip install m3u8

# Copia el directorio actual (que contiene tu código fuente) en el contenedor en /app
COPY . .